<?php

/**
 * @file
 * Commerce order cleanup variables user interface module.
 */


/**
 * Implements hook_menu().
 */
function commerce_order_cleanup_vars_ui_menu() {
  $items = array();

  $items['admin/commerce/config/order-cleanup-vars-ui'] = array(
    'title' => 'Commerce order cleanup vars UI',
    'description' => 'Provide a page listing variables created for use with Commerce Order Cleanup.',
    'page callback' => 'commerce_order_cleanup_vars_ui_summary',
    'access arguments' => array('view commerce order cleanup vars'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'commerce_order_cleanup_vars_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function commerce_order_cleanup_vars_ui_permission() {
  return array(
    'view commerce order cleanup vars' => array(
      'title' => t('View commerce order cleanup variables list'),
    ),
  );
}